#!/bin/bash

# Install dotfiles
./dotfiles.sh

# Install wslconfig
win/wslconfig.sh

# Install binaries
bin/install.sh

# Install packages from apt
packages/apt.sh

# Set up and install packages from brew
packages/brew.sh

# Set up and install packages from NPM
packages/npm.sh

# Set up Conda + Python
monty/install.sh